#!/bin/bash
set -e
set -o pipefail

ssh_cmd="ssh -T"

oper_dir="operational-processing"
trans_dir="transition-scripts"
cnetpy_dir="cloudnetpy"
git_dir="git-for-deploy"
hook="hooks/post-receive"
prod_server="cloudnet@altocumulus.fmi.fi"

read -p "Are all tests passing? (y/N, answering y will start the deployment): " answer
if [ "$answer" != "y" ]; then
    exit 4
fi

$ssh_cmd $prod_server << EOF
rm -rf $git_dir
mkdir $git_dir $oper_dir $trans_dir $cnetpy_dir
cd $git_dir
git init --bare $oper_dir.git
git init --bare $trans_dir.git
git init --bare $cnetpy_dir.git
EOF

for DIR in $cnetpy_dir $trans_dir $oper_dir
do
    sed -i 's/FOO/'$DIR'/g' $hook
    echo
    echo "Pushing " $DIR " to production..."
    scp $hook $prod_server:~/$git_dir/$DIR.git/hooks
    sed -i 's/'$DIR'/FOO/g' $hook
    cd ../$DIR
    git remote add production $prod_server:$git_dir/$DIR.git
    git push production master
    git remote rm production
    echo
    echo "Installing ..."
    $ssh_cmd $prod_server << EOF
cd $DIR
python3 -m venv venv
source venv/bin/activate
pip3 install --upgrade pip
pip3 install --force-reinstall .
deactivate
EOF

    cd ../$oper_dir
done

echo
echo "Make sure operational-processing uses up-to-date CloudnetPy"
$ssh_cmd $prod_server << EOF
source $oper_dir/venv/bin/activate
pip3 install --upgrade pip
cd $cnetpy_dir
pip3 install . --force-reinstall
deactivate
EOF

echo
echo "Deployed!"
exit 0



