from setuptools import setup, find_packages


setup(name='data_processing',
      description='Software for running Cloudnet processing.',
      author='Finnish Meteorological Institute',
      license='MIT License',
      install_requires=['cloudnetpy_qc>=0.0.11',
                        'cloudnetpy>=1.29.1',
                        'cloudnetme>=0.1.5',
                        'pytest',
                        'pylint',
                        'mypy',
                        'requests',
                        'requests_mock',
                        'types-pytz',
                        'types-requests',
                        'types-urllib3',
                        ],
      include_package_data=True,
      package_dir={"": "src"},
      packages=find_packages(where="src"),
      python_requires='>=3.8',
      classifiers=[
          "Programming Language :: Python :: 3.8",
          "License :: OSI Approved :: MIT License",
          "Intended Audience :: Science/Research",
          "Topic :: Scientific/Engineering",
      ],
      )
