#!/bin/bash
TARGET="/home/cloudnet/operational-processing"
GIT_DIR="/home/cloudnet/git-for-deploy/operational-processing.git"
BRANCH="master"

while read oldrev newrev ref
do
  if [ "$ref" = "refs/heads/$BRANCH" ];
  then
    echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
    git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
  else
    echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
  fi
done
