[global]
instruments = [
  "chm15k",
  "hatpro",
  "rpg-fmcw-94",
]

[[configs]]
id = "chm15k"
vars = [
  "temp_int",
  "temp_ext",
  "temp_det",
  "temp_lom",
]

[[configs]]
id = "hatpro"
vars = [
  "ambient_Target1_temperature",
  "ambient_Target2_temperature",
  "receiver1_temperature",
  "receiver2_temperature",
]

[[configs]]
id = "hatpro-hkd"
vars = [
  "Alarm",
  "T0",
  "T1",
  "T2",
  "T3",
  "Stab0",
  "Stab1",
  "Flash",
  "QFLWP1",
  "QFLWP2",
  "QFIWV1",
  "QFIWV2",
  "QFDLY1",
  "QFDLY2",
  "QFHPC1",
  "QFHPC2",
  "QFTPC1",
  "QFTPC2",
  "QFTPB1",
  "QFTPB2",
  "QFSTA1",
  "QFSTA2",
  "QFLPR1",
  "QFLPR2",
  "HPCh1",
  "HPCh2",
  "HPCh3",
  "HPCh4",
  "HPCh5",
  "HPCh6",
  "HPCh7",
  "TPCh1",
  "TPCh2",
  "TPCh3",
  "TPCh4",
  "TPCh5",
  "TPCh6",
  "TPCh7",
  "RF",
  "DB",
  "BLM",
  "SCa",
  "GCa",
  "NCa",
  "ND1",
  "ND2",
  "R1St",
  "R2St",
  "PF",
  "TarSt",
  "NDSt",
]

[[configs]]
id = "rpg-fmcw-94"
vars = [
  "TransT",
  "RecT",
  "EnvTemp",
  "DDVolt",
  "PCT",
  "TransPow",
  "Status",
]
