[format.chm15k_nc]
vars.temp_int = "internal_temperature"
vars.temp_ext = "external_temperature"
vars.temp_det = "detector_temperature"
vars.temp_lom = "laser_optic_module_temperature"
vars.life_time = "life_time"
vars.state_laser = "laser_quality"
vars.state_detector = "detector_quality"
vars.state_optics = "optical_quality"

[format.hatpro_nc]
vars.ambient_Target1_temperature = "ambient_target_sensor1_temperature"
vars.ambient_Target2_temperature = "ambient_target_sensor2_temperature"
vars.receiver1_temperature = "humidity_profiler_temperature"
vars.receiver2_temperature = "temperature_profiler_temperature"

[format.hatpro_hkd]
vars.Alarm = "alarm"
vars.T0 = "ambient_target_sensor1_temperature"
vars.T1 = "ambient_target_sensor2_temperature"
vars.T2 = "humidity_profiler_temperature"
vars.T3 = "temperature_profiler_temperature"
vars.Stab0 = "humidity_profiler_stability"
vars.Stab1 = "temperature_profiler_stability"
vars.Flash = "remaining_flash_memory"
vars.QFLWP1 = "lwp_quality_level"
vars.QFLWP2 = "lwp_quality_reason"
vars.QFIWV1 = "iwv_quality_level"
vars.QFIWV2 = "iwv_quality_reason"
vars.QFDLY1 = "dly_quality_level"
vars.QFDLY2 = "dly_quality_reason"
vars.QFHPC1 = "hpc_quality_level"
vars.QFHPC2 = "hpc_quality_reason"
vars.QFTPC1 = "tpc_quality_level"
vars.QFTPC2 = "tpc_quality_reason"
vars.QFTPB1 = "tpb_quality_level"
vars.QFTPB2 = "tpb_quality_reason"
vars.QFSTA1 = "sta_quality_level"
vars.QFSTA2 = "sta_quality_reason"
vars.QFLPR1 = "lpr_quality_level"
vars.QFLPR2 = "lpr_quality_reason"
vars.HPCh1 = "humidity_profiler_channel1_status"
vars.HPCh2 = "humidity_profiler_channel2_status"
vars.HPCh3 = "humidity_profiler_channel3_status"
vars.HPCh4 = "humidity_profiler_channel4_status"
vars.HPCh5 = "humidity_profiler_channel5_status"
vars.HPCh6 = "humidity_profiler_channel6_status"
vars.HPCh7 = "humidity_profiler_channel7_status"
vars.TPCh1 = "temperature_profiler_channel1_status"
vars.TPCh2 = "temperature_profiler_channel2_status"
vars.TPCh3 = "temperature_profiler_channel3_status"
vars.TPCh4 = "temperature_profiler_channel4_status"
vars.TPCh5 = "temperature_profiler_channel5_status"
vars.TPCh6 = "temperature_profiler_channel6_status"
vars.TPCh7 = "temperature_profiler_channel7_status"
vars.RF = "rain_flag"
vars.DB = "dew_blower_speed_status"
vars.BLM = "boundary_layer_mode_status"
vars.SCa = "sky_tipping_calibration_status"
vars.GCa = "gain_calibration_status"
vars.NCa = "noise_calibration_status"
vars.ND1 = "humidity_profiler_noise_diode_status"
vars.ND2 = "temperature_profiler_noise_diode_status"
vars.R1St = "humidity_profiler_stability_status"
vars.R2St = "temperature_profiler_stability_status"
vars.PF = "power_failure_status"
vars.TarSt = "ambient_target_stability_status"
vars.NDSt = "noise_diode_status"

[format.rpg-fmcw-94_lv1]
vars.RecT = "receiver_temperature"
vars.EnvTemp = "environment_temperature"
vars.DDVolt = "direct_detection_voltage"
vars.PCT = "pc_temperature"
vars.TransPow = "transmitter_power"
vars.TransT = "transmitter_temperature"

[metadata.hatpro]
vars.alarm.description = "The alarm flag is activated in the following cases:\n\n- interference or failure of a channel that is used in one of the retrievals\n- thermal receiver stability not sufficient for measurement\n- noise diode failure of one of the receivers\n- ambient target thermal sensor not stable"
vars."*_temperature".unit = "K"
vars."*_stability".unit = "K"
vars.remaining_flash_memory.unit = "kB"
vars."*_quality_level".description = "‘0’ = this level 2 product is not evaluated for quality control\n\n‘1’ = highest quality level\n\n‘2’ = reduced quality\n\n‘3’ = low quality. This sample should not be used."
vars."*_quality_reason".description = "‘0’ = unknown\n\n‘1’ = possible external interference on a receiver channel or failure of a receiver channel that is used in the retrieval of this product.\n\n‘2’ = LWP too high. At high rain rates the scattering on rain drops can mask the water vapour line completely and no humidity profiling or IWV determination is possible. Also the temperature profiling may be affected when the oxygen line channels are all saturated due to droplets.\n\n‘3’ = free for future use."
vars."*_profiler_channel*_status".description = "When a bit is set ‘1’, the corresponding channel is ok, otherwise the channel has a malfunction."
vars.rain_flag.description = "‘1’ means raining, ‘0’ = no rain"
vars.dew_blower_speed_status.description = "‘1’ = high speed mode, ‘0’ = low speed mode"
vars.boundary_layer_mode_status.description = "‘1’ = boundary layer scanning active, ‘0’ = BL-mode not active"
vars.sky_tipping_calibration_status.description = "‘1’ = sky tipping calibration running, ‘0’ = not active"
vars.gain_calibration_status.description = "‘1’ = gain calibration running (using internal ambient target), ‘0’ = not active"
vars.noise_calibration_status.description = "‘1’ = noise calibration running, ‘0’ = not active"
vars.humidity_profiler_noise_diode_status.description = " ‘1’ = noise diode of humidity profiler ok, ‘0’ = noise diode not working"
vars.temperature_profiler_noise_diode_status.description = "‘1’ = noise diode of temperature profiler ok, ‘0’ = noise diode not working"
vars."*_profiler_stability_status".description = "‘0’ = unknown, not enough data samples recorded yet, ‘1’ = stability ok, ‘2’ = not sufficiently stable"
vars.power_failure_status.description = "‘1’ = a power failure has occurred recently. When a new MDF has been started automatically after a power failure, the ‘1’ flag is kept for 1000 seconds and switching back to ‘0’ afterwards. ‘0’ = no power failure occurred."
vars.ambient_target_stability_status.description = "Some radiometers are using two ambient target temperature sensors for monitoring the target’s physical temperature. When the temperature readings of these two sensors differ by more than 0.3 K, the flag turns to ‘1’. ‘0’ = sensors ok."
vars.noise_diode_status.description = "‘0’ = noise diode is turned off for the current sample, ‘1’ = noise diode is turned on for the current sample."

[metadata.rpg-fmcw-94]
vars.receiver_temperature.description = "Receiver temperature of current sample"
vars.receiver_temperature.unit = "K"
vars.environment_temperature.description = "Environment temperature of current sample"
vars.environment_temperature.unit = "K"
vars.direct_detection_voltage.description = "Direct detection channel voltage of current sample"
vars.direct_detection_voltage.unit = "V"
vars.pc_temperature.description = "PC temperature of current sample"
vars.pc_temperature.unit = "K"
vars.transmitter_power.description = "Transmitter power of current sample"
vars.transmitter_power.unit = "K"
vars.transmitter_temperature.description = "Transmitter temperature of current sample"
vars.transmitter_temperature.unit = "K"

[metadata.chm15k]
vars.internal_temperature.unit = "K"
vars.external_temperature.unit = "K"
vars.detector_temperature.unit = "K"
vars.laser_optic_module_temperature.unit = "K"
vars.life_time.description = "Laser operating hours"
vars.life_time.unit = "h"
vars.laser_quality.description = "Laser quality index"
vars.laser_quality.unit = "percent"
vars.detector_quality.description = "Quality of detector signal"
vars.detector_quality.unit = "percent"
vars.optical_quality.description = "Optical quality index"
vars.optical_quality.unit = "percent"
