name: Test and lint
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint
        run: docker run --env-file test.env test pylint **/*.py --errors-only --ignored-modules=netCDF4

      - name: Check type hints
        run: docker run --env-file test.env test /bin/bash -c "mypy --ignore-missing-imports --check-untyped-defs scripts/ src/"

      - name: Test
        run: docker run --env-file test.env test pytest

      - name: Run e2e tests
        run: docker run --env-file e2e-test.env test /bin/sh -c 'for f in tests/e2e/*/main.py; do $f || exit; done'
