name: Test and lint
on: [push]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t test .

      - name: Test
        run: docker run --env-file test.env test pytest

      - name: Run e2e tests
        run: docker run --env-file e2e-test.env test /bin/sh -c 'for f in tests/e2e/*/main.py; do $f || exit; done'

      - name: Lint
        run: docker run --env-file test.env test pylint **/*.py --errors-only --ignored-modules=netCDF4
