name: Test and lint

on: [push, pull_request]

jobs:
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: latest
          target: prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install .[dev]
      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run unit tests
        run: python -m pytest tests/unit
